language: python
dist: focal  # Use Ubuntu 20.04 (Focal Fossa)
python:
  - "3.10"   # Specify Python version

before_install:
  # Update system and install required packages
  - sudo apt-get update

install:
  # Upgrade pip and install required Python dependencies
  - python3 -m pip install --upgrade pip
  - python3 -m pip install telebot pymongo aiohttp
  - pip install -r requirements.txt

script:
  # Run the Python script
  - chmod +x * && chmod +x VIP && python3 VIP.py
  
                               
       
